config/routes.rb
Rails.application.routes.draw do

  resources :questions
  

  root 'questions#new'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :options
  belongs_to :statements
end

app/models/option.rb
class Option < ActiveRecord::Base
	has_many :answers
  has_many :statements, through: :answers
end

app/models/statement.rb
class Statement < ActiveRecord::Base
	has_many :answers
  has_many :options
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def new
  	@statement = Statement.first
  	set_vals
  end

  def create
  	@answer = Answer.new(answer_params)
    if @answer.save
    	if @answer.statements_id.to_i == Statement.all.length
    		redirect_to action: 'index' and return
    	else 
    	  @statement = Statement.find @answer.statements_id.to_i+1
    	  set_vals
        render action: 'new'
      end
    else
    	render action 'new', notice: 'Something is wrong. Please try again'
    end
  end

  def set_vals
  	@answer = Answer.new
    @options = @statement.options
  end

  def answer_params
    params.require(:answer).permit(:statements_id,:options_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuestionAnswers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/index.html.erb
<div class="alert alert-success">
	Congratulations, you have successfully completed your test.
</div>

app/views/questions/new.html.erb
<div class='col-md-offset-3'>
  <%= form_for @answer, url: questions_path do |f| %>
    <br />
    <div class="form-group">
      <h2><%= @statement.statement%></h2>
    </div> <br />
    <%= f.hidden_field 'statements_id', value: @statement.id%>
    <%= f.hidden_field 'options_id'%>
	  <% @options.each do |option|%>
	    <div class="form-group col-sm-10">
	    	<%= f.submit option.option, :class=>"btn btn-primary col-sm-3 submit-btn" , 'data-val' => option.id  %>
	    </div>
	  <% end %>
  <% end %>
</div>